version: '3.3'

services:

    wordpress:
        image: wordpress
        restart: always
        ports:
            - 9000:80
        environment:
            WORDPRESS_DB_HOST: db
            WORDPRESS_DB_USER: dbuser
            WORDPRESS_DB_PASSWORD: dbpass
            WORDPRESS_DB_NAME: hoatk_blog
        volumes:
            - ${PWD}/wordpress:/var/www/html

    db:
        image: mysql:5.7
        restart: always
        environment:
            MYSQL_DATABASE: hoatk_blog
            MYSQL_USER: dbuser
            MYSQL_PASSWORD: dbpass
            MYSQL_RANDOM_ROOT_PASSWORD: '1'
        volumes:
            - ${PWD}/db:/var/lib/mysql

volumes:
    wordpress:
    db: