title: Quick Note
description: Take notes.
baseurl: ""
url: "http://blog.cuongnd.info"
repository: nguyenduycuong/Profiles
paginate: 28

banner: "/assets/res/banner.png" # site banner (load when someone share your page url)
favicon: "/assets/res/favicon.png" # site's favicon (icon left side of your page)

# MatJek specific configurations
user:
  name: "Nguyễn Duy Cường"
  email: "cuongnd.ami@gmail.com"
  website: "blog.cuongnd.info"
  avatar: "/assets/res/user.png"
  github: "NguyenDuyCuong"
google_tracking_id: ""
google_site_verification: ""
disqus_shortname: blog-cuongnd-info

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title


plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-archives
  - jekyll-redirect-from
  - redcarpet
  - jekyll-gist
  - pygments.rb

exclude:
  - Gemfile
  - Gemfile.lock

sass:
  style: compressed

  future: true