version: "3"
services:
  blogcuongndinfo:
    image: jekyll/builder:latest
    command: jekyll serve --watch --force_polling --verbose
    volumes:
      - ${PWD}:/srv/jekyll
      - ${PWD}/bundle:/usr/local/bundle
    ports:
      - 8000:4000